### ISSUE TITLE
Travis CI compilation time

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#33]
Hey @dgasmith ,

I updated the travis script and the tests. Now I use python to compare the files.
In any case, there is something I don't understand. To compile the code without optimizations with g++ in my machine takes less than a minute. However, travis seems to need way more time. Any idea why?

Thanks!

**Comment by dgasmith** [comment]
Travis CI is giving you free compute time which is nice; however, they give you old virtualized (docker) Google CE (or maybe AWS?) instances which are not very fast. You can get faster or slower depending on which node you pick up. Compiling on Travis CI has always been quite slow relative to a native computer. Sometimes I wonder if the issue is IO not compute...

**Comment by chemphys** [comment]
Solved, closing issue.
